"""
Email Notifier Agent.

Responsibilities:
  1. Receive the AI-generated issues_report from LangGraph state.
  2. Connect to the Gmail MCP server to dispatch a formatted email notification.
  3. Send to the recipient configured in NOTIFICATION_EMAIL env var.
  4. Confirm delivery and update the email_sent flag in graph state.
"""

import os
from langchain_aws import ChatBedrock
from langchain_core.messages import SystemMessage
from langchain.agent import create_agent
from tools.email_tools import get_email_mcp_tools
from dotenv import load_dotenv

load_dotenv()


SYSTEM_PROMPT = """You are an email notification assistant.

You will receive a GitHub issues analysis report. Your job is to:
1. Compose a professional HTML email with:
   - Subject: "GitHub Issues Analysis Report — <repo name>"
   - A brief 2-sentence intro explaining this is an automated AI analysis
   - The full report content, well-formatted
   - A footer: "Generated by GitHub Issue Analyzer & Email Notifier"

2. Send the email to: {recipient}

3. After sending, confirm with:
   "✅ Email report successfully sent to {recipient}"

Use the send_email MCP tool to dispatch the message.
"""


async def build_email_notifier_agent():
    """
    Build and return a react agent that uses Gmail MCP tools + Bedrock LLM.

    Returns:
        A compiled LangGraph react agent ready for ainvoke().
    """
    recipient = os.environ.get("EMAIL_RECIPIENT", "")

    llm = ChatBedrock(
        model_id="anthropic.claude-3-5-sonnet-20241022-v2:0",
        region_name=os.environ.get("AWS_DEFAULT_REGION", ""),
        model_kwargs={"max_tokens": 2048, "temperature": 0.0},
    )

    email_tools = await get_email_mcp_tools()

    agent = create_agent(
        model=llm,
        tools=email_tools,
        state_modifier=SystemMessage(
            content=SYSTEM_PROMPT.format(recipient=recipient)
        ),
    )

    return agent
